### ISSUE TITLE
Level Dependancy

### ISSUE THREAD

**Issue by WORMSS** [ekristen/node-github-cache#1]
Is it possible to not use level dependency?
I keep trying to install your module, and it fails on leveldown which is a dependency on level.
It wants to do something with python for some reason and seems to fail on a windows machine.

**Comment by ekristen** [comment]
Level is what is used to store the cached data, so its a requirement. 

Nothing actually requires python, however `leveldown` and a few others have native C++ bindings which are built with `node-gyp` which uses python.

**Comment by WORMSS** [comment]
I've just installed Python, and now it's asking to install .NET 2.0 SDK and Visual Studio 2005
Is there no alternative, as every time I install Visual Studio, I end up having to format 2 weeks later to remove all the crap that it installs as its impossible to remove it all again?

**Comment by ekristen** [comment]
Ah Windows. That explains it.  Well level, leveldown, and levelup uses native C++ bindings that have to be compiled. 

I do not use windows. If you'd like to figure out how to make it work and submit a pull request that supports windows and doesn't break anything else, I'd be ok with merging that.

I have thought about allowing someone to pass an object that had certain methods to allow custom data stores, but I have not had the cycles or interest from other people using the project to warrant the work at the moment.

**Comment by ekristen** [comment]
For what it is worth, level works on windows, you just have to have the proper developer tools installed to be able to compile the dependencies.

**Comment by WORMSS** [comment]
So far I've downloaded the repo, and replaced level with memdown and changed the import to require('memdown');

No actual runtime errors, but always comes back with undefined data at the moment.. So I am just having a look at that.

memdown is meant to be a direct drop in for leveldown, I am not sure if its a direct drop in for level. It's what I am investigating now.

I wouldn't even mind if I could find something that uses a inefficient require('fs'), as long as it does not require all this extra baggage like python+visual studio.

**Comment by ekristen** [comment]
FWIW -- https://github.com/TooTallNate/node-gyp#installation -- Unfortunately certain developer tools are required to work with node.js, and there are thousands more modules that require `node-gyp` which will require compilation tools.

**Comment by WORMSS** [comment]
Well I will need to find the ones that do not require it. This is the first one I've encountered so far.

**Comment by WORMSS** [comment]
I'm not sure why, but

``` javascript
github.events.getFromUserOrg({ 'user': user, 'org': org }, onGetFromUserOrg);
```

doesn't work, always comes back with ("Error: Not Found", undefined), but 

``` javascript
github.events._getFromUserOrg({ 'user': user, 'org': org }, onGetFromUserOrg);
```

does work. 

I think the problem is its not a dropin. The get code always returns an error.

``` javascript
self.cachedb.get(cache_id + ':tag', {valueEncoding: 'utf8'}, function(err, tag) {
console.log(err, tag); // [Error: NotFound] undefined which then quits out.
```

I am guessing there is extra stuff I need to pass to memdown to start it caching in the first place.. But I have not learnt what that is yet.

**Comment by ekristen** [comment]
If you are replacing cachedb object, you need a `get` and `put` method, that is about it. Get takes a single key argument, put takes a keyname and the data to associate with it. data going in should be serialized json, data coming out of get should be automatically deserialized json.

**Comment by WORMSS** [comment]
I might see about decoupling the database completely and having it as a pass in object via the setup object. That way I can do a man in the middle and see what the heck is going on. 

Thank you for the signature for the `get` and `put`, I will keep you up to date with what I find going on, hopefully I will get something working nicely.

**Comment by WORMSS** [comment]
I found the problem. Memdown's error did not contain `err.status = '404';` Something so simple but completely passed me.
So I have jerry rigged that in for now, see if there is a more universal way to try and figure this out.

Now to figure out how the actual storing is working as it is returning a Buffer. :+1:

**Comment by ralphtheninja** [comment]
This turned into an interesting thread. Keep posting your progress! :)

**Comment by WORMSS** [comment]
Yep, I hate MemDown too.. I have in the end completely ripped out the 'default' leveldb variable and relying solely on your `this.config.cachedb`.
This is obviously nowhere near a 'FULL' implementation. It barely even be classed as a 'hack', but this is my simple alternative for now as it's close to midnight and I've been coding one thing or another since 7:45am.

``` javascript
function MyDB() {
    this._store = {};
}
MyDB.prototype.db = ''; // Required to make github-cache not fail over to using the built-in.
MyDB.prototype.put = function (key, value, options, callback) {
    this._store[key] = value;
    setImmediate(callback, null);
};
MyDB.prototype.get = function (key, options, callback) {
    if ( key in this._store ) {
        var value = this._store[key];
        setImmediate(callback, null, value);
    } else {
        setImmediate(callback, {'status': '404'});
    }
};
MyDB.prototype.batch = function (array, callback) {
    for ( var i = 0, length = array.length; i < length; i++ ) {
        this._store[array[i].key] = array[i].value;
    }
    setImmediate(callback);
};
```

**Comment by area** [comment]
I've replaced leveldb with redis in my branch at http://github.com/area/node-github-cache

I note test 12 doesn't pass, but nor does it in this version, so I've left it for now.

**Comment by WORMSS** [comment]
Very nice.. I am swamped under at work in at the moment, but once I can breathe again, I will definitely have a look.

**Comment by ekristen** [comment]
I think that someone needs to create a libkv for node.js that supports consul, redis, level, etc, zookeeper, etc ... then we can abstract this away.
