### ISSUE TITLE
Can't use pagination methods from Github

### ISSUE THREAD

**Issue by natecavanaugh** [ekristen/node-github-cache#19]
Hi there,
I've been using the module for a while now, but I've found one issue I'm not sure what the best way around it is, but it's that the [pagination methods from the Github module](https://github.com/mikedeboer/node-github/blob/master/examples/getAllPages.js) don't work on a cached request, and from what I can tell, it's because the headers aren't saved anywhere, so it can't access the [link header](https://developer.github.com/v3/#link-header) from the request, so it throws an error.

Is there any way to accomplish this?

Thanks!

**Comment by ekristen** [comment]
Can you show me how you are using it? Using pages has worked for me in the past but I haven't tested lately.

**Comment by natecavanaugh** [comment]
I'm using bluebird to promisify all of the methods (all of which works fine, since it doesn't mutate the data in anyway), but here's an example method call:

``` js
var myRepos = github.getAllPages(
        github.repos.getAllAsync,
    {
        per_page: 100,
        type: 'owner'
    }
);
```

I also get the same errors if I use the regular API as well.

**Comment by ekristen** [comment]
I'm not at my computer at the moment but the get AllAsync looks custom? Is it? I don't recall that being in the API.

**Comment by natecavanaugh** [comment]
It's from bluebird's promisification, so the method that accepts the callback is `github.repos.getAll`, and bluebird's method is `github.repos.getAllAsync`.

But I should have stripped it down to eliminate Bluebird in my example, but here's the default way (throws the same error):

``` js
github.getAllPages(
    github.repos.getAll,
    {
        per_page: 10, //set to 10 just to force it to paginate
        type: 'owner'
    },
    function(err, res) {
        console.log('callback response', err, res);
    }
);
```

The exact error I get is:
`Uncaught TypeError: Cannot read property 'link' of undefined`

Let me know if you need any other info.

**Comment by natecavanaugh** [comment]
Oh yeah, it might also work on the first request, just because since it's not cached, it would have the header, but all subsequent requests to the cache don't have the header, so it bombs out trying to read it.

**Comment by ekristen** [comment]
@natecavanaugh so I was only checking the emails on this issue because I've been on vacation. Looks like you gave me links in the first issue. I know what is going on now.

I believe the getAllPages is a relatively new function, at least new to me, and I never accounted for its behavior.

It looks like it wants to see the meta object on the end of each request. Up until this point I've always stripped the metadata on cached requests. I think I'll try and modify it to give the etag, a status of 304 to indicate its cached and the link field. This shouldn't break any existing functionality, but need to do some testing.

I'll make the changes and publish a version to the @next tag and let you know when it is up.

**Comment by ekristen** [comment]
@natecavanaugh I just pushed the `next` branch. Give it a try, works for me locally. I didn't try every combination, but this adds back in the meta object its looking for, just slightly modified, with a cached result, I don't return any of the x- headers and I change the status to 304 Not Modified

**Comment by natecavanaugh** [comment]
@ekristen Thanks a lot for looking at this while on vacation, as well as the fix.

I just tested it out locally, and it all seems to be working :)

Thanks again!

**Comment by ekristen** [comment]
I'll publish the update to npm soon.

**Comment by ekristen** [comment]
Resolved by https://github.com/ekristen/node-github-cache/commit/d3fb26e48701375dfa9eb161565f468ae393dcd4

**Comment by ekristen** [comment]
@natecavanaugh looks like version 2.0.0 was just published and they just yanked the getAllPages helper methods entirely :( 

I'm looking at releasing a newer version of this library that will let you pass in your own version for the github api lib instead of having to use the one the comes with it.

**Comment by natecavanaugh** [comment]
@ekristen I actually really like that idea as well :) The last upgrade of node-github-cache broke for me because of the underlying major change in node-github, but your update had it as a minor.

I think allowing us to pass in any lib we like gives us a lot of safety and freedom, so def a 👍 from me :)

Thanks for the heads up!

**Comment by ekristen** [comment]
Interesting ... what broke? (just curious) 

AFAIK, all the updates I have delivered have only upped the minor version of github library. I haven't delivered a version supporting 2.0.0 yet.

**Comment by natecavanaugh** [comment]
I went from 1.0.1 of github-cache to 1.3.0, in which time, and your dep on github went from 0.2.4 to 1.1.0.

So, according to semver rules, I believe that a minor upgrade just means additive, non-breaking changes, but since github-cache is a proxy, technically your API broke as well.

(That, and since I'm using my own CacheDB implementation, I didn't have the batch method, but that was totally my fault).

Overall, it wasn't a huge issue, just a bit of a surprise :)

Thanks again!

**Comment by ekristen** [comment]
Sorry about that, I definitely try not to break things ;)

I'm working on my next major version which will have the following changes ...
1. support any version of github that you want to use (theoretically, but there may be some edge cases)
2. most likely use https://github.com/ekristen/node-libkv so you can use more than just level (if you'd like to look into creating a wrapper for couchdb for libkv, that'd be awesome)

Any comments, questions, or other would be appreciated.
