### ISSUE TITLE
Support iojs@3.x (and upcoming Node 4.x)

### ISSUE THREAD

**Issue by bajtos** [ekristen/node-github-cache#3]
The current version of node-github-cache depends on an old version of `level`, which depends on an old version of `leveldown`, which does not compile on iojs@3.x.

Can you/we please upgrade this module to depend on the latest version of `level` (i.e. 1.3.0), since that version supports iojs@3.x?

Related: #2

**Comment by ekristen** [comment]
Hi @bajtos, just committed https://github.com/ekristen/node-github-cache/commit/18aa5db62ea10e9c06cccf1f48f758768a710d87, please test out the master branch for me, let me know if you run into any issues, if you do not, I'll cut version `0.6.0` and push it to the npm registry.

**Comment by bajtos** [comment]
Oh, looks like you have already upgraded level to `^1.3` in v0.5, even though the PR #2 is still open. Sorry for the confusion!

Our project is using v0.3, which seems to have a different API than v0.5, I'll have to update our project to v0.5 first.

I confirm that I can `npm install` from master on iojs@3.1, thus I think this issue can be closed as resolved.

BTW is there any particular reason why this module is still in 0.x version? It would be great to bump the version to 1.0 (or higher), so that npm's carrot operator (^) can automatically pick up upgrades.

**Comment by ekristen** [comment]
1.0.0 published and tagged

**Comment by bajtos** [comment]
> 1.0.0 published and tagged

Awesome :tada: thank you :smile:
